# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\QC\Desktop\IonTrap-WIPM-master\IonTrap-WIPM-master\GUI_Material\QC2_1TEST.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 743)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 60, 441, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(30, 10, 491, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 340, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(30, 70, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.radioButton_rabi_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_rabi_1.setGeometry(QtCore.QRect(330, 380, 151, 19))
        self.radioButton_rabi_1.setObjectName("radioButton_rabi_1")
        self.radioButton_zeeman_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_zeeman_1.setGeometry(QtCore.QRect(330, 440, 141, 19))
        self.radioButton_zeeman_1.setObjectName("radioButton_zeeman_1")
        self.radioButton_cust = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_cust.setGeometry(QtCore.QRect(330, 500, 115, 19))
        self.radioButton_cust.setObjectName("radioButton_cust")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 580, 111, 61))
        self.pushButton.setObjectName("pushButton")
        self.radioButton_off = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_off.setGeometry(QtCore.QRect(330, 530, 115, 19))
        self.radioButton_off.setChecked(True)
        self.radioButton_off.setObjectName("radioButton_off")
        self.Setting = QtWidgets.QTabWidget(self.centralwidget)
        self.Setting.setGeometry(QtCore.QRect(30, 110, 441, 231))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Setting.setFont(font)
        self.Setting.setObjectName("Setting")
        self.DPL_Cooling = QtWidgets.QWidget()
        self.DPL_Cooling.setObjectName("DPL_Cooling")
        self.doubleSpinBox_DPL = QtWidgets.QDoubleSpinBox(self.DPL_Cooling)
        self.doubleSpinBox_DPL.setGeometry(QtCore.QRect(120, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_DPL.setFont(font)
        self.doubleSpinBox_DPL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_DPL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_DPL.setMaximum(999999.99)
        self.doubleSpinBox_DPL.setObjectName("doubleSpinBox_DPL")
        self.label_36 = QtWidgets.QLabel(self.DPL_Cooling)
        self.label_36.setGeometry(QtCore.QRect(200, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.DPL_Cooling)
        self.label_37.setGeometry(QtCore.QRect(20, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.Laser_397_1_DPL = QtWidgets.QCheckBox(self.DPL_Cooling)
        self.Laser_397_1_DPL.setGeometry(QtCore.QRect(140, 90, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_397_1_DPL.setFont(font)
        self.Laser_397_1_DPL.setChecked(True)
        self.Laser_397_1_DPL.setObjectName("Laser_397_1_DPL")
        self.Laser_397_2_DPL = QtWidgets.QCheckBox(self.DPL_Cooling)
        self.Laser_397_2_DPL.setGeometry(QtCore.QRect(210, 90, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_397_2_DPL.setFont(font)
        self.Laser_397_2_DPL.setChecked(True)
        self.Laser_397_2_DPL.setObjectName("Laser_397_2_DPL")
        self.Laser_397_3_DPL = QtWidgets.QCheckBox(self.DPL_Cooling)
        self.Laser_397_3_DPL.setGeometry(QtCore.QRect(280, 90, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_397_3_DPL.setFont(font)
        self.Laser_397_3_DPL.setChecked(True)
        self.Laser_397_3_DPL.setObjectName("Laser_397_3_DPL")
        self.Laser_397_main_DPL = QtWidgets.QCheckBox(self.DPL_Cooling)
        self.Laser_397_main_DPL.setGeometry(QtCore.QRect(20, 90, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_397_main_DPL.setFont(font)
        self.Laser_397_main_DPL.setChecked(True)
        self.Laser_397_main_DPL.setObjectName("Laser_397_main_DPL")
        self.Laser_866_DPL = QtWidgets.QCheckBox(self.DPL_Cooling)
        self.Laser_866_DPL.setGeometry(QtCore.QRect(20, 120, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_866_DPL.setFont(font)
        self.Laser_866_DPL.setChecked(True)
        self.Laser_866_DPL.setObjectName("Laser_866_DPL")
        self.Laser_854_DPL = QtWidgets.QCheckBox(self.DPL_Cooling)
        self.Laser_854_DPL.setGeometry(QtCore.QRect(20, 150, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_854_DPL.setFont(font)
        self.Laser_854_DPL.setChecked(True)
        self.Laser_854_DPL.setObjectName("Laser_854_DPL")
        self.line_2 = QtWidgets.QFrame(self.DPL_Cooling)
        self.line_2.setGeometry(QtCore.QRect(10, 60, 411, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.DPL_Cooling)
        self.line_4.setGeometry(QtCore.QRect(100, 90, 20, 81))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_44 = QtWidgets.QLabel(self.DPL_Cooling)
        self.label_44.setGeometry(QtCore.QRect(140, 120, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.DPL_Cooling)
        self.label_45.setGeometry(QtCore.QRect(140, 150, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.Setting.addTab(self.DPL_Cooling, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_41 = QtWidgets.QLabel(self.tab_6)
        self.label_41.setGeometry(QtCore.QRect(20, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_40 = QtWidgets.QLabel(self.tab_6)
        self.label_40.setGeometry(QtCore.QRect(180, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.doubleSpinBox_OP = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.doubleSpinBox_OP.setGeometry(QtCore.QRect(100, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_OP.setFont(font)
        self.doubleSpinBox_OP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_OP.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_OP.setMaximum(999999.99)
        self.doubleSpinBox_OP.setObjectName("doubleSpinBox_OP")
        self.Laser_729_1_OP = QtWidgets.QCheckBox(self.tab_6)
        self.Laser_729_1_OP.setGeometry(QtCore.QRect(140, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_729_1_OP.setFont(font)
        self.Laser_729_1_OP.setObjectName("Laser_729_1_OP")
        self.Laser_729_3_OP = QtWidgets.QCheckBox(self.tab_6)
        self.Laser_729_3_OP.setGeometry(QtCore.QRect(280, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_729_3_OP.setFont(font)
        self.Laser_729_3_OP.setObjectName("Laser_729_3_OP")
        self.Laser_729_2_OP = QtWidgets.QCheckBox(self.tab_6)
        self.Laser_729_2_OP.setGeometry(QtCore.QRect(210, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_729_2_OP.setFont(font)
        self.Laser_729_2_OP.setObjectName("Laser_729_2_OP")
        self.Laser_729_4_OP = QtWidgets.QCheckBox(self.tab_6)
        self.Laser_729_4_OP.setGeometry(QtCore.QRect(350, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_729_4_OP.setFont(font)
        self.Laser_729_4_OP.setObjectName("Laser_729_4_OP")
        self.Laser_854_OP = QtWidgets.QCheckBox(self.tab_6)
        self.Laser_854_OP.setGeometry(QtCore.QRect(20, 160, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_854_OP.setFont(font)
        self.Laser_854_OP.setCheckable(True)
        self.Laser_854_OP.setChecked(True)
        self.Laser_854_OP.setObjectName("Laser_854_OP")
        self.line_3 = QtWidgets.QFrame(self.tab_6)
        self.line_3.setGeometry(QtCore.QRect(10, 100, 411, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Laser_729_main_OP = QtWidgets.QCheckBox(self.tab_6)
        self.Laser_729_main_OP.setGeometry(QtCore.QRect(20, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_729_main_OP.setFont(font)
        self.Laser_729_main_OP.setChecked(True)
        self.Laser_729_main_OP.setObjectName("Laser_729_main_OP")
        self.line_5 = QtWidgets.QFrame(self.tab_6)
        self.line_5.setGeometry(QtCore.QRect(100, 130, 20, 51))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_46 = QtWidgets.QLabel(self.tab_6)
        self.label_46.setGeometry(QtCore.QRect(140, 160, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.doubleSpinBox_SB = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.doubleSpinBox_SB.setGeometry(QtCore.QRect(320, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_SB.setFont(font)
        self.doubleSpinBox_SB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_SB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_SB.setMaximum(999999.99)
        self.doubleSpinBox_SB.setObjectName("doubleSpinBox_SB")
        self.label_53 = QtWidgets.QLabel(self.tab_6)
        self.label_53.setGeometry(QtCore.QRect(400, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab_6)
        self.label_54.setGeometry(QtCore.QRect(240, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.doubleSpinBox_OPSBrepeat = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.doubleSpinBox_OPSBrepeat.setGeometry(QtCore.QRect(100, 60, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_OPSBrepeat.setFont(font)
        self.doubleSpinBox_OPSBrepeat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_OPSBrepeat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_OPSBrepeat.setMaximum(999999.99)
        self.doubleSpinBox_OPSBrepeat.setObjectName("doubleSpinBox_OPSBrepeat")
        self.label_56 = QtWidgets.QLabel(self.tab_6)
        self.label_56.setGeometry(QtCore.QRect(180, 60, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab_6)
        self.label_57.setGeometry(QtCore.QRect(20, 60, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.Setting.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.Laser_729_4_opreating = QtWidgets.QCheckBox(self.tab_7)
        self.Laser_729_4_opreating.setGeometry(QtCore.QRect(350, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_729_4_opreating.setFont(font)
        self.Laser_729_4_opreating.setObjectName("Laser_729_4_opreating")
        self.Laser_729_main_opreating = QtWidgets.QCheckBox(self.tab_7)
        self.Laser_729_main_opreating.setGeometry(QtCore.QRect(20, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_729_main_opreating.setFont(font)
        self.Laser_729_main_opreating.setChecked(True)
        self.Laser_729_main_opreating.setObjectName("Laser_729_main_opreating")
        self.Laser_729_1_opreating = QtWidgets.QCheckBox(self.tab_7)
        self.Laser_729_1_opreating.setGeometry(QtCore.QRect(140, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_729_1_opreating.setFont(font)
        self.Laser_729_1_opreating.setObjectName("Laser_729_1_opreating")
        self.Laser_854_opreating = QtWidgets.QCheckBox(self.tab_7)
        self.Laser_854_opreating.setGeometry(QtCore.QRect(20, 120, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_854_opreating.setFont(font)
        self.Laser_854_opreating.setChecked(True)
        self.Laser_854_opreating.setObjectName("Laser_854_opreating")
        self.line_6 = QtWidgets.QFrame(self.tab_7)
        self.line_6.setGeometry(QtCore.QRect(100, 90, 20, 51))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.Laser_729_2_opreating = QtWidgets.QCheckBox(self.tab_7)
        self.Laser_729_2_opreating.setGeometry(QtCore.QRect(210, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_729_2_opreating.setFont(font)
        self.Laser_729_2_opreating.setObjectName("Laser_729_2_opreating")
        self.label_47 = QtWidgets.QLabel(self.tab_7)
        self.label_47.setGeometry(QtCore.QRect(180, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.doubleSpinBox_opreating = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.doubleSpinBox_opreating.setGeometry(QtCore.QRect(100, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_opreating.setFont(font)
        self.doubleSpinBox_opreating.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_opreating.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_opreating.setMaximum(999999.99)
        self.doubleSpinBox_opreating.setObjectName("doubleSpinBox_opreating")
        self.Laser_729_3_opreating = QtWidgets.QCheckBox(self.tab_7)
        self.Laser_729_3_opreating.setGeometry(QtCore.QRect(280, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Laser_729_3_opreating.setFont(font)
        self.Laser_729_3_opreating.setObjectName("Laser_729_3_opreating")
        self.label_48 = QtWidgets.QLabel(self.tab_7)
        self.label_48.setGeometry(QtCore.QRect(20, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.tab_7)
        self.label_49.setGeometry(QtCore.QRect(140, 120, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.line_7 = QtWidgets.QFrame(self.tab_7)
        self.line_7.setGeometry(QtCore.QRect(10, 60, 411, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_58 = QtWidgets.QLabel(self.tab_7)
        self.label_58.setGeometry(QtCore.QRect(230, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.doubleSpinBox_opreating_2 = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.doubleSpinBox_opreating_2.setGeometry(QtCore.QRect(310, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_opreating_2.setFont(font)
        self.doubleSpinBox_opreating_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_opreating_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_opreating_2.setMaximum(999999.99)
        self.doubleSpinBox_opreating_2.setObjectName("doubleSpinBox_opreating_2")
        self.label_59 = QtWidgets.QLabel(self.tab_7)
        self.label_59.setGeometry(QtCore.QRect(390, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.Setting.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.doubleSpinBox_PMT = QtWidgets.QDoubleSpinBox(self.tab_8)
        self.doubleSpinBox_PMT.setGeometry(QtCore.QRect(100, 20, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_PMT.setFont(font)
        self.doubleSpinBox_PMT.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_PMT.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_PMT.setMaximum(999999.99)
        self.doubleSpinBox_PMT.setObjectName("doubleSpinBox_PMT")
        self.label_51 = QtWidgets.QLabel(self.tab_8)
        self.label_51.setGeometry(QtCore.QRect(20, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab_8)
        self.label_52.setGeometry(QtCore.QRect(180, 20, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.Setting.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_55 = QtWidgets.QLabel(self.tab_9)
        self.label_55.setGeometry(QtCore.QRect(30, 20, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.Setting.addTab(self.tab_9, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(30, 380, 271, 281))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget_2.setUsesScrollButtons(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(100, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.spinBox_zeemanrepeat_4 = QtWidgets.QSpinBox(self.tab_3)
        self.spinBox_zeemanrepeat_4.setGeometry(QtCore.QRect(150, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.spinBox_zeemanrepeat_4.setFont(font)
        self.spinBox_zeemanrepeat_4.setObjectName("spinBox_zeemanrepeat_4")
        self.doubleSpinBox_zeemanend_2 = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_zeemanend_2.setGeometry(QtCore.QRect(150, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_zeemanend_2.setFont(font)
        self.doubleSpinBox_zeemanend_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_zeemanend_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_zeemanend_2.setMaximum(999999.99)
        self.doubleSpinBox_zeemanend_2.setObjectName("doubleSpinBox_zeemanend_2")
        self.doubleSpinBox_zeemanstart_2 = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_zeemanstart_2.setGeometry(QtCore.QRect(20, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_zeemanstart_2.setFont(font)
        self.doubleSpinBox_zeemanstart_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_zeemanstart_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_zeemanstart_2.setMaximum(999999.99)
        self.doubleSpinBox_zeemanstart_2.setObjectName("doubleSpinBox_zeemanstart_2")
        self.label_31 = QtWidgets.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(150, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setGeometry(QtCore.QRect(20, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_38 = QtWidgets.QLabel(self.tab_3)
        self.label_38.setGeometry(QtCore.QRect(100, 110, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_50 = QtWidgets.QLabel(self.tab_3)
        self.label_50.setGeometry(QtCore.QRect(20, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_60 = QtWidgets.QLabel(self.tab_3)
        self.label_60.setGeometry(QtCore.QRect(230, 110, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.doubleSpinBox_zeemanstep_2 = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_zeemanstep_2.setGeometry(QtCore.QRect(20, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_zeemanstep_2.setFont(font)
        self.doubleSpinBox_zeemanstep_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_zeemanstep_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_zeemanstep_2.setMaximum(999999.99)
        self.doubleSpinBox_zeemanstep_2.setObjectName("doubleSpinBox_zeemanstep_2")
        self.label_62 = QtWidgets.QLabel(self.tab_3)
        self.label_62.setGeometry(QtCore.QRect(230, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.tab_3)
        self.label_63.setGeometry(QtCore.QRect(150, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_63.setFont(font)
        self.label_63.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_63.setObjectName("label_63")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setGeometry(QtCore.QRect(230, 110, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.spinBox_zeemanrepeat = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_zeemanrepeat.setGeometry(QtCore.QRect(20, 200, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.spinBox_zeemanrepeat.setFont(font)
        self.spinBox_zeemanrepeat.setObjectName("spinBox_zeemanrepeat")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(100, 110, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(150, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(20, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.doubleSpinBox_zeemanend = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_zeemanend.setGeometry(QtCore.QRect(150, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_zeemanend.setFont(font)
        self.doubleSpinBox_zeemanend.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_zeemanend.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_zeemanend.setMaximum(999999.99)
        self.doubleSpinBox_zeemanend.setObjectName("doubleSpinBox_zeemanend")
        self.doubleSpinBox_zeemanstep = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_zeemanstep.setGeometry(QtCore.QRect(20, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_zeemanstep.setFont(font)
        self.doubleSpinBox_zeemanstep.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_zeemanstep.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_zeemanstep.setMaximum(999999.99)
        self.doubleSpinBox_zeemanstep.setObjectName("doubleSpinBox_zeemanstep")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(150, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.doubleSpinBox_zeemanstart = QtWidgets.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_zeemanstart.setGeometry(QtCore.QRect(20, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_zeemanstart.setFont(font)
        self.doubleSpinBox_zeemanstart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_zeemanstart.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_zeemanstart.setMaximum(999999.99)
        self.doubleSpinBox_zeemanstart.setObjectName("doubleSpinBox_zeemanstart")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(100, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(230, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.spinBox_zeemanrepeat_2 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_zeemanrepeat_2.setGeometry(QtCore.QRect(150, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.spinBox_zeemanrepeat_2.setFont(font)
        self.spinBox_zeemanrepeat_2.setObjectName("spinBox_zeemanrepeat_2")
        self.spinBox_zeemanrepeat_3 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_zeemanrepeat_3.setGeometry(QtCore.QRect(150, 200, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.spinBox_zeemanrepeat_3.setFont(font)
        self.spinBox_zeemanrepeat_3.setObjectName("spinBox_zeemanrepeat_3")
        self.line_8 = QtWidgets.QFrame(self.tab_4)
        self.line_8.setGeometry(QtCore.QRect(20, 150, 231, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(20, 170, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(150, 170, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(100, 200, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_42 = QtWidgets.QLabel(self.tab_4)
        self.label_42.setGeometry(QtCore.QRect(230, 200, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        self.label_28.setGeometry(QtCore.QRect(100, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setGeometry(QtCore.QRect(150, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.doubleSpinBox_custTime = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_custTime.setGeometry(QtCore.QRect(150, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_custTime.setFont(font)
        self.doubleSpinBox_custTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_custTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_custTime.setMaximum(999999.99)
        self.doubleSpinBox_custTime.setObjectName("doubleSpinBox_custTime")
        self.doubleSpinBox_custF = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_custF.setGeometry(QtCore.QRect(20, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.doubleSpinBox_custF.setFont(font)
        self.doubleSpinBox_custF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_custF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_custF.setMaximum(999999.99)
        self.doubleSpinBox_custF.setObjectName("doubleSpinBox_custF")
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(20, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(230, 40, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.spinBox_custreapeat = QtWidgets.QSpinBox(self.tab_5)
        self.spinBox_custreapeat.setGeometry(QtCore.QRect(20, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.spinBox_custreapeat.setFont(font)
        self.spinBox_custreapeat.setObjectName("spinBox_custreapeat")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(20, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(100, 110, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(400, 50, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.radioButton_zeeman_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_zeeman_2.setGeometry(QtCore.QRect(330, 470, 141, 19))
        self.radioButton_zeeman_2.setObjectName("radioButton_zeeman_2")
        self.radioButton_rabi_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_rabi_2.setGeometry(QtCore.QRect(330, 410, 181, 19))
        self.radioButton_rabi_2.setObjectName("radioButton_rabi_2")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(400, 40, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 505, 23))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuAdvance = QtWidgets.QMenu(self.menubar)
        self.menuAdvance.setObjectName("menuAdvance")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionreset = QtWidgets.QAction(MainWindow)
        self.actionreset.setObjectName("actionreset")
        self.actionClear_Settings = QtWidgets.QAction(MainWindow)
        self.actionClear_Settings.setObjectName("actionClear_Settings")
        self.actionClear_Data = QtWidgets.QAction(MainWindow)
        self.actionClear_Data.setObjectName("actionClear_Data")
        self.actionPaulse_Shaping = QtWidgets.QAction(MainWindow)
        self.actionPaulse_Shaping.setObjectName("actionPaulse_Shaping")
        self.actionDDS_Controller = QtWidgets.QAction(MainWindow)
        self.actionDDS_Controller.setObjectName("actionDDS_Controller")
        self.menuMain.addAction(self.actionreset)
        self.menuMain.addAction(self.actionClear_Settings)
        self.menuMain.addAction(self.actionClear_Data)
        self.menuAdvance.addAction(self.actionPaulse_Shaping)
        self.menuAdvance.addAction(self.actionDDS_Controller)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuAdvance.menuAction())

        self.retranslateUi(MainWindow)
        self.Setting.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#000000;\">Ion Trap QC Control System 2.1</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#002800;\">Mode</span></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#002800;\">Basic Setting</span></p></body></html>"))
        self.radioButton_rabi_1.setText(_translate("MainWindow", "Rabi Scan (unshaped)"))
        self.radioButton_zeeman_1.setText(_translate("MainWindow", "Zeeman Scan (DDS)"))
        self.radioButton_cust.setText(_translate("MainWindow", "Customized"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.radioButton_off.setText(_translate("MainWindow", "OFF"))
        self.label_36.setText(_translate("MainWindow", "us"))
        self.label_37.setText(_translate("MainWindow", "Doppler Cooling"))
        self.Laser_397_1_DPL.setText(_translate("MainWindow", "397_1"))
        self.Laser_397_2_DPL.setText(_translate("MainWindow", "397_2"))
        self.Laser_397_3_DPL.setText(_translate("MainWindow", "397_3"))
        self.Laser_397_main_DPL.setText(_translate("MainWindow", "397 Main"))
        self.Laser_866_DPL.setText(_translate("MainWindow", "866"))
        self.Laser_854_DPL.setText(_translate("MainWindow", "854"))
        self.label_44.setText(_translate("MainWindow", "NA"))
        self.label_45.setText(_translate("MainWindow", "NA"))
        self.Setting.setTabText(self.Setting.indexOf(self.DPL_Cooling), _translate("MainWindow", "DPL Cooling"))
        self.label_41.setText(_translate("MainWindow", "Optical Pump"))
        self.label_40.setText(_translate("MainWindow", "us"))
        self.Laser_729_1_OP.setText(_translate("MainWindow", "729_1"))
        self.Laser_729_3_OP.setText(_translate("MainWindow", "729_3"))
        self.Laser_729_2_OP.setText(_translate("MainWindow", "729_2"))
        self.Laser_729_4_OP.setText(_translate("MainWindow", "729_4"))
        self.Laser_854_OP.setText(_translate("MainWindow", "854"))
        self.Laser_729_main_OP.setText(_translate("MainWindow", "729 Main"))
        self.label_46.setText(_translate("MainWindow", "NA"))
        self.label_53.setText(_translate("MainWindow", "us"))
        self.label_54.setText(_translate("MainWindow", "SB Cooling"))
        self.label_56.setText(_translate("MainWindow", "times"))
        self.label_57.setText(_translate("MainWindow", "Repeat"))
        self.Setting.setTabText(self.Setting.indexOf(self.tab_6), _translate("MainWindow", "Opt Pump SB Cooling"))
        self.Laser_729_4_opreating.setText(_translate("MainWindow", "729_4"))
        self.Laser_729_main_opreating.setText(_translate("MainWindow", "729 Main"))
        self.Laser_729_1_opreating.setText(_translate("MainWindow", "729_1"))
        self.Laser_854_opreating.setText(_translate("MainWindow", "854 1"))
        self.Laser_729_2_opreating.setText(_translate("MainWindow", "729_2"))
        self.label_47.setText(_translate("MainWindow", "mV"))
        self.Laser_729_3_opreating.setText(_translate("MainWindow", "729_3"))
        self.label_48.setText(_translate("MainWindow", "Amplitude"))
        self.label_49.setText(_translate("MainWindow", "NA"))
        self.label_58.setText(_translate("MainWindow", "<html><head/><body><p>Frequency</p></body></html>"))
        self.label_59.setText(_translate("MainWindow", "MHz"))
        self.Setting.setTabText(self.Setting.indexOf(self.tab_7), _translate("MainWindow", "Opreating"))
        self.label_51.setText(_translate("MainWindow", "Detecting"))
        self.label_52.setText(_translate("MainWindow", "us"))
        self.Setting.setTabText(self.Setting.indexOf(self.tab_8), _translate("MainWindow", "Detecting"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p>Temporarily we couple the operation period to the frequency </p><p>of 50Hz, if you want to change or cancle it, please change </p><p>the code responsible for running.(not in the GUI file)</p></body></html>"))
        self.Setting.setTabText(self.Setting.indexOf(self.tab_9), _translate("MainWindow", "Gap"))
        self.label_18.setText(_translate("MainWindow", "us"))
        self.label_31.setText(_translate("MainWindow", "Repeat"))
        self.label_32.setText(_translate("MainWindow", "Time for Step"))
        self.label_38.setText(_translate("MainWindow", "us"))
        self.label_50.setText(_translate("MainWindow", "Time to Start"))
        self.label_60.setText(_translate("MainWindow", "times"))
        self.label_62.setText(_translate("MainWindow", "us"))
        self.label_63.setText(_translate("MainWindow", "Time to End"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Rabi Scan"))
        self.label_19.setText(_translate("MainWindow", "times"))
        self.label_12.setText(_translate("MainWindow", "Hz"))
        self.label_13.setText(_translate("MainWindow", "Repeat"))
        self.label_15.setText(_translate("MainWindow", "Frequency for Step"))
        self.label_14.setText(_translate("MainWindow", "Frequency of End"))
        self.label_16.setText(_translate("MainWindow", "Hz"))
        self.label_17.setText(_translate("MainWindow", "Hz"))
        self.label_11.setText(_translate("MainWindow", "Frequency of Start"))
        self.label_24.setText(_translate("MainWindow", "Amplitude"))
        self.label_25.setText(_translate("MainWindow", "Zeeman Time"))
        self.label_26.setText(_translate("MainWindow", "mV"))
        self.label_42.setText(_translate("MainWindow", "us"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Zeeman Scan"))
        self.label_28.setText(_translate("MainWindow", "Hz"))
        self.label_21.setText(_translate("MainWindow", "Rabi Time"))
        self.label_29.setText(_translate("MainWindow", "Repeat"))
        self.label_23.setText(_translate("MainWindow", "us"))
        self.label_22.setText(_translate("MainWindow", "Frequency "))
        self.label_27.setText(_translate("MainWindow", "times"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Costomized"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-style:italic; color:#000000;\">WIPM，CAS</span><span style=\" font-style:italic; color:#000000;\"/></p></body></html>"))
        self.radioButton_zeeman_2.setText(_translate("MainWindow", "Zeeman Scan (AWG)"))
        self.radioButton_rabi_2.setText(_translate("MainWindow", "Rabi Scan (shaped)"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt; font-style:italic; color:#000000;\">Ion Trap Lab</span></p></body></html>"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuAdvance.setTitle(_translate("MainWindow", "Advance"))
        self.actionreset.setText(_translate("MainWindow", "Introduction"))
        self.actionClear_Settings.setText(_translate("MainWindow", "Clear Settings"))
        self.actionClear_Data.setText(_translate("MainWindow", "Clear Data"))
        self.actionPaulse_Shaping.setText(_translate("MainWindow", "Paulse Shaping"))
        self.actionDDS_Controller.setText(_translate("MainWindow", "DDS Controller"))
